NAME_VALUE(LED, 1, 0),
    NAME_VALUE(BUZZER, 1, 1),
    NAME_VALUE(LDR, 1, 2),
    NAME_VALUE(LINE, 1, 3),
    NAME_VALUE(SERVO, 1, 4),
    NAME_VALUE(HCSR04, 2, 5),
    NAME_VALUE(NULLDEVICE, 0, 6)
